### ISSUE TITLE
Nested structure

### ISSUE THREAD

**Issue by queryluke** [trln/proto-argot#2]
As I've been digging into traject, I've found a bit of a gotcha with the nested structure. If you run one of the marc records through, you'll see the author part of the resulting JSON looks like this:

```
"authors": [
    {
      "sort": "Breinholt, Thomas. drt pro.   Soul & science electronic resource the power of the mind produced and directed by Thomas Breinholt, Danish Radio",
      "main": [
        {
          "name": "Breinholt, Thomas.",
          "vernacular": null,
          "marc_source": "100"
        }
      ],
      "director": [
        {
          "name": "Breinholt, Thomas.",
          "vernacular": null,
          "marc_source": "100"
        }
      ],
      "other": [
        {
          "name": "Danmarks radio.",
          "vernacular": null,
          "marc_source": "710"
        }
      ]
    }
  ],
```

Note that it's an array containing a single hash/object (with nested properties). So, we can do a nested structure, but the top level accumulator of traject will always be an array.

@adjam Do you see this as a problem?

**Comment by adjam** [comment]
why yes, yes it is ... see #3 

We will probably have to come up with a new Traject writer.

**Comment by adjam** [comment]
The output of traject will have to be filtered through a "flattener" or "de-arrayifier" but obviously we don't want that happening on all the fields.  What I think will work is something like recording all the fields that are allowed to be arrays.  The following doesn't handle nested values, but it's a start.  I'm not sure if it's the best rubying either.

``` ruby
require 'set'

array_fields = Set.new(%w[holdings collection]) # or %w[holdings collection].to_set

def flatten_record!(rec)
  rec.each do |key,value| 
     if not array_fields.include?(key)
        if value.is_a?(Array) 
            rec[key] = value[0]
        end
    end 
  end
end
```

**Comment by adjam** [comment]
Why this is a problem:  any code that processes the format is going to have to use array lookups on the top-level fields, and if the field might not even be there this gets annoying pretty quickly.  

The good news is we don't need to handle nested paths, since this only happens with the fields output by traject, and those are all at the top level.  

Options:

1) live with it (puts a slightly higher burden on validation and enhancement)
2) flatten before we send in to the central processor, either
- with a special traject writer, or
- with a post-processing step after traject 

3) flatten at the outer edge of the processor

**Comment by queryluke** [comment]
Digging around a bit more, I found [context.output_hash](https://github.com/traject/traject/blob/c23d2045d49ca60be6b70a19e471e739e86b1d51/doc/indexing_rules.md#each_record)

Though they explicitly say "Do not assign anything other than an array", assigning an object does not throw any errors. I wonder why everything in the resulting json needs to be an array...

**Comment by adjam** [comment]
I think that's there because the internal stuff that handles the data expects it to be an array.  That call makes sense, because it simplifies the code, and Solr doesn't care. 

This is one reason to only "flatten" once the data is past Traject and into our own domain.
